Swe\Compenent\Invoice\Model\InvoiceItem:
    properties:
        object:
                - NotBlank: { message: "Ce champ ne doit pas étre vide" }
                - Type:
                            type : string
                            message: "This field is required."
        quantity:
                - Type:
                            type : numeric
                            message: "This field must be a valid quantity"

        amount:
            - NotBlank: { message: "This field is required" }
            - Type:
                   type : numeric
                   message: "This field must be a valid amount"
            
            
Swe\Compenent\Invoice\Model\Invoice:
    properties:
        designation:
                - NotBlank: { message: "This field is required" }
                - Type:
                            type : string
                            message: Cette valeur doit être une chaine de caractères  
        amount:
                - NotBlank: { message: "This field is required" }
                - Type:
                    type : numeric 
                    message: "This field must be a valid amount"
        dateInvoicing:
                - NotBlank: { message: "This field is required" }
                - Type:
                    type : date
                    message: "This field must be a valid date"
                    
                
    
        